=== arielcostas/vigo360-fuentes/public/dataset/fuentes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
	El contenido de este archivo estÃ¡ cedido bajo una licencia
	CC BY-SA 4.0 https://creativecommons.org/licenses/by-sa/4.0/
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="fuentes">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="fuente" type="tipo_fuente" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="tipo_fuente">
		<xs:sequence>
			<xs:element name="titulo" type="xs:string" />
			<xs:element name="ubicacion" type="tipo_ubicacion" />
			<xs:element name="caudal" type="tipo_caudal" />
			<xs:element name="calidad" type="tipo_calidad" />
			<xs:element name="origen" type="xs:string" />
			<xs:element name="lavadero" type="xs:boolean" />
			<xs:element name="analizada" minOccurs="0" type="xs:gYear" />
			<xs:element name="nota" minOccurs="0" type="xs:string" />
		</xs:sequence>
		<xs:attribute name="id" use="required" type="tipo_id" id="id" />
	</xs:complexType>

	<xs:complexType name="tipo_ubicacion">
		<xs:sequence>
			<xs:element name="lugar" type="xs:string" />
			<xs:element name="parroquia" type="xs:string" />
			<xs:element name="latitud" type="xs:string" />
			<xs:element name="longitud" type="xs:string" />
		</xs:sequence>
	</xs:complexType>

	<xs:simpleType name="tipo_id">
		<xs:restriction base="xs:string">
			<xs:pattern value="(SC)?[0-9]{1,3}[A-Z]?(\/\d{2,3})?"></xs:pattern>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="tipo_caudal">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Bajo" />
			<xs:enumeration value="Medio" />
			<xs:enumeration value="Alto" />
			<xs:enumeration value="Ninguno" />
			<xs:enumeration value="Con llave de paso" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="tipo_calidad">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Sin calificar" />
			<xs:enumeration value="Mala" />
			<xs:enumeration value="Media" />
			<xs:enumeration value="Buena" />
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== arielcostas/vigo360-fuentes/public/dataset/fuentes.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--
	El contenido de este archivo está cedido bajo una licencia
	CC BY-SA 4.0 https://creativecommons.org/licenses/by-sa/4.0/
-->
<fuentes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://fuentes.vigo360.es/dataset/fuentes.xsd">
	<fuente id="30">
		<titulo>Fonte do Abade - Bembrive</titulo>
		<ubicacion>
			<lugar>Rúa de Mandín, 68</lugar>
			<parroquia>Bembrive</parroquia>
			<latitud>42.206319</latitud>
			<longitud>-8.678782</longitud>
		</ubicacion>
		<caudal>Con llave de paso</caudal>
		<calidad>Media</calidad>
		<origen>Referido a unas tierras propiedad de la parroquia de Bembrive (de hecho la casa rectoral se encontraba enfrente), y por extensión, al párroco o abad. Hasta 1999 se conocía como Fonte dos Freires.</origen>
		<lavadero>true</lavadero>
		<analizada>1969</analizada>
	</fuente>
	<fuente id="308">
		<titulo>Fonte do Abade - Coruxo</titulo>
		<ubicacion>
			<lugar>Camiño da Taberna, 19</lugar>
			<parroquia>Coruxo</parroquia>
			<latitud>42.185754</latitud>
			<longitud>-8.777277</longitud>
		</ubicacion>
		<caudal>Con llave de paso</caudal>
		<calidad>Mala</calidad>
		<origen>Referido al lugar donde se encuentra, cuyas tierras eran propiedad de la iglesia de Coruxo, y por extensión de su párroco o abad.</origen>
		<lavadero>false</lavadero>
		<analizada>1984</analizada>
	</fuente>
	<fuente id="248">
		<titulo>Fonte de Abalde</titulo>
		<ubicacion>
			<lugar>Rúa da Lagoa, 56 (ramal)</lugar>
			<parroquia>Beade</parroquia>
			<latitud>42.199991</latitud>
			<longitud>-8.701124</longitud>
		</ubicacion>
		<caudal>Bajo</caudal>
		<calidad>Mala</calidad>
		<origen>Referido al lugar donde se encuentra, Abalde (mal normativizado como Balde), que tiene su origen en un antropónimo medieval de posesor (Villam Abaldi), que significa las tierras de Abaldus o Avaldus (entre el siglo V y X). El origen del apellido Abalde se encuentra en este lugar.</origen>
		<lavadero>true</lavadero>
		<analizada>1980</analizada>
	</fuente>
	<fuente id="444">
		<titulo>Fonte da Abelleira</titulo>
		<ubicacion>
			<lugar>Sendero entre Fragoselo y el Parque Forestal de Coruxo</lugar>
			<parroquia>Coruxo</parroquia>
			<latitud>42.17521</latitud>
			<longitud>-8.772438</longitud>
		</ubicacion>
		<caudal>Ninguno</caudal>
		<calidad>Mala</calidad>
		<origen>Referido a un lugar donde se criaban las abejas, ya sea de forma salvaje o para producir miel.</origen>
		<lavadero>false</lavadero>
		<analizada>1997</analizada>
	</fuente>
	<fuente id="430">
		<titulo>Fonte da Abilleira</titulo>
		<ubicacion>
			<lugar>Rúa do Abade Juan de Bastos (al pasar la VG-20)</lugar>
			<parroquia>Matamá</parroquia>
			<latitud>42.187317</latitud>
			<longitud>-8.734799</longitud>
		</ubicacion>
		<caudal>Medio</caudal>
		<calidad>Mala</calidad>
		<origen>Referido a un lugar donde se criaban las abejas, ya sea de forma salvaje o para producir miel.</origen>
		<lavadero>false</lavadero>
		<analizada>1997</analizada>
	</fuente>
	<fuente id="315">
		<titulo>Fonte do Agrón</titulo>
		<ubicacion>
			<lugar>Avenida de Ricardo Mella, cruce Camiño da Verdella</lugar>
			<parroquia>Oia</parroquia>
			<latitud>42.18373</latitud>
			<longitud>-8.808073</longitud>
		</ubicacion>
		<caudal>Medio</caudal>
		<calidad>Media</calidad>
		<origen>Referido a un agro (terreno cercado destinado a cultivo) más grande del entorno.</origen>
		<lavadero>false</lavadero>
		<analizada>1985</analizada>
	</fuente>
	<fuente id="232">
		<titulo>Fonte da Aguadiña</titulo>
		<ubicacion>
			<lugar>Rúa da Aguadiña, 19</lugar>
			<parroquia>Lavadores</parroquia>
			<latitud>42.233907</latitud>
			<longitud>-8.68722</longitud>
		</ubicacion>
		<caudal>Bajo</caudal>
		<calidad>Mala</calidad>
		<origen>Referido al lugar donde se encuentra, A Aguadiña, referido a una zona húmeda y con tendencia a estar cubierta de lama.</origen>
		<lavadero>true</lavadero>
		<analizada>1980</analizada>
	</fuente>
	<fuente id="364">
		<titulo>Fonte de Alén</titulo>
		<ubicacion>
			<lugar>Camiño do Alén, 24</lugar>
			<parroquia>Beade</parroquia>
			<latitud>42.193045</latitud>
			<longitud>-8.700861</longitud>
		</ubicacion>
		<caudal>Bajo</caudal>
		<calidad>Media</calidad>
		<origen>Esta fuente se conoce como A Fonte do Regueiro, referido a un pequeño río de agua que atraviesa el lugar, y como A Fonte de Chanes, en referencia a un apodo de un antiguo propietario de los terrenos donde se encuentra. El topónimo Alén, del que toma actualmente el nombre, hace referencia a unos campos situados más allá de un obstáculo.</origen>
		<lavadero>false</lavadero>
		<analizada>1988</analizada>
	</fuente>
	<fuente id="159">
		<titulo>Fonte do Alto da Garrida</titulo>
		<ubicacion>
			<lugar>Estrada do Monte Alba, 6</lugar>
			<parroquia>Valadares</parroquia>
			<latitud>42.165264</latitud>
			<longitud>-8.72045</longitud>
		</ubicacion>
		<caudal>Bajo</caudal>
		<calidad>Media</calidad>
		<origen>Referido al Alto da Garrida, donde se encuentra.</origen>
		<lavadero>true</lavadero>
		<analizada>1973</analizada>
	</fuente>
	<fuente id="55">
		<titulo>Fonte do Ameal</titulo>
		<ubicacion>
			<lugar>Rúa do Ameal, 11</lugar>
			<parroquia>Cabral</parroquia>
			<latitud>42.232542</latitud>
			<longitud>-8.638303</longitud>
		</ubicacion>
		<caudal>Medio</caudal>
		<calidad>Mala</calidad>
		<origen>Referido a la presencia de amieiros, alisos, un árbol que abunda en lugares húmedos.</origen>
		<lavadero>true</lavadero>
		<analizada>1969</analizada>
	</fuente>
	<fuente id="416">
		<titulo>Fonte das Amieiras</titulo>
		<ubicacion>
			<lugar>Estrada de Bembrive, 157</lugar>
			<parroquia>Bembrive</parroquia>
			<latitud>42.206738</latitud>
			<longitud>-8.692617</longitud>
		</ubicacion>
		<caudal>Alto</caudal>
		<calidad>Mala</calidad>
		<origen>Referido a la presencia de amieiros, alisos, un árbol que abunda en lugares húmedos. Antaño esta fuente se ubicaba más hacia el oeste, y esta fuente se creó por iniciativa vecinal, encañándose las aguas hacia aquí.</origen>
		<lavadero>false</lavadero>
		<analizada>1995</analizada>
	</fuente>
	<fuente id="925">
		<titulo>Fonte dos Amieiros</titulo>
		<ubicacion>
			<lugar>Final del Camiño das Figueiras</lugar>
			<parroquia>Cabral</parroquia>
			<latitud>42.229273</latitud>
			<longitud>-8.664317</longitud>
		</ubicacion>
		<caudal>Medio</caudal>
		<calidad>Mala</calidad>
		<origen>Referido a la presencia de amieiros, alisos, un árbol que abunda en lugares húmedos.</origen>
		<lavadero>false</lavadero>
		<analizada>2006</analizada>
	</fuente>
	<fuente id="482">
		<titulo>Fonte das Amilleiras</titulo>
		<ubicacion>
			<lugar>Camiño da Esqueiriña, 5</lugar>
			<parroquia>Candeán</parroquia>
			<latitud>42.241691</latitud>
			<longitud>-8.650521</longitud>
		</ubicacion>
		<caudal>Bajo</caudal>
		<calidad>Buena</calidad>
		<origen>Referido a las tierras inmediatas conocidas como A Millada, que reciben el nombre por dedicarse al cultivo de millo, cereal.</origen>
		<lavadero>false</lavadero>
	</fuente>
	<fuente id="27">
		<titulo>Fonte das Aradas</titulo>
		<ubicacion>
			<lugar>Camiño das Aradas, 1</lugar>
			<parroquia>Bembrive</parroquia>
			<latitud>42.205236</latitud>
			<longitud>-8.673659</longitud>
		</ubicacion>
		<caudal>Bajo</caudal>
		<calidad>Media</calidad>
		<origen>Referido a unas tierras cultivadas mediante la técnica del arado, es decir, abriendo surcos en la tierra.</origen>
		<lavadero>false</lavadero>
		<analizada>1972</analizada>
	</fuente>
	<fuente id="202">
		<titulo>Fonte da Arnela</titulo>
		<ubicacion>
			<lugar>Rúa da Arnela, 83</lugar>
			<parroquia>Teis</parroquia>
			<latitud>42.254952</latitud>
			<longitud>-8.686798</longitud>
		</ubicacion>
		<caudal>Bajo</caudal>
		<calidad>Media</calidad>
		<origen>Referido al lugar de Arnela, topónimo que hace referencia a varios ríos que discurren por el lugar y que hacen que sea unas tierras húmedas.</origen>
		<lavadero>true</lavadero>
		<analizada>1973</analizada>
	</fuente>
	<fuente id="371">
		<titulo>Fonte das Aspras</titulo>
		<ubicacion>
			<lugar>Camiño das Aspras, 9</lugar>
			<parroquia>Cabral</parroquia>
			<latitud>42.233814</latitud>
			<longitud>-8.660858</longitud>
		</ubicacion>
		<caudal>Bajo</caudal>
		<calidad>Mala</calidad>
		<origen>Referido posiblemente a unas tierras ásperas, difíciles de cultivar.</origen>
		<lavadero>false</lavadero>
	</fuente>
	<fuente id="103">
		<titulo>Fonte do Auditorio</titulo>
		<ubicacion>
			<lugar>Parque de Castrelos</lugar>
			<parroquia>Castrelos</parroquia>
			<latitud>42.214233</latitud>
			<longitud>-8.729705</longitud>
		</ubicacion>
		<caudal>Medio</caudal>
		<calidad>Buena</calidad>
		<origen>Toma el nombre del Auditorio de Castrelos, que está justo al lado</origen>
		<lavadero>false</lavadero>
		<analizada>1969</analizada>
	</fuente>
	<fuente id="427">
		<titulo>Fonte da Balsa</titulo>
		<ubicacion>
			<lugar>Estrada da Balsa, 8</lugar>
			<parroquia>Matamá</parroquia>
			<latitud>42.198843</latitud>
			<longitud>-8.742986</longitud>
		</ubicacion>
		<caudal>Medio</caudal>
		<calidad>Buena</calidad>
		<origen>Referido al barrio de A Balsa, cuyo topónimo tiene su origen en que esta zona era bastante húmeda.</origen>
		<lavadero>true</lavadero>
		<analizada>1997</analizada>
	</fuente>
	<fuente id="100">
		<titulo>Fonte da Balsa de Arriba</titulo>
		<ubicacion>
			<lugar>Estrada da Balsa, 85</lugar>
			<parroquia>Matamá</parroquia>
			<latitud>42.196413</latitud>
			<longitud>-8.743411</longitud>
		</ubicacion>
		<caudal>Medio</caudal>
		<calidad>Media</calidad>
		<origen>Referido al barrio de A Balsa, cuyo topónimo tiene su origen en que esta zona era bastante húmeda.</origen>
		<lavadero>true</lavadero>
		<analizada>1969</analizada>
	</fuente>
	<fuente id="300">
		<titulo>Fonte de Balvís</titulo>
		<ubicacion>
			<lugar>Rúa de Manuel Cominges, 59</lugar>
			<parroquia>Matamá</parroquia>
			<latitud>42.197718</latitud>
			<longitud>-8.733652</longitud>
